// Code generated by 'yaegi extract github.com/456vv/x/smtp'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"github.com/456vv/x/smtp"
	"reflect"
)

func init() {
	Symbols["github.com/456vv/x/smtp/smtp"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"PlainAuth": reflect.ValueOf(smtp.PlainAuth),

		// type definitions
		"Info": reflect.ValueOf((*smtp.Info)(nil)),
		"Smtp": reflect.ValueOf((*smtp.Smtp)(nil)),
	}
}
