// Code generated by 'yaegi extract github.com/88250/lute'. DO NOT EDIT.

package yaegi_lib

import (
	"github.com/88250/lute"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/88250/lute/lute"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"FormatNode":         reflect.ValueOf(lute.FormatNode),
		"New":                reflect.ValueOf(lute.New),
		"RenderNodeBlockDOM": reflect.ValueOf(lute.RenderNodeBlockDOM),
		"Version":            reflect.ValueOf(constant.MakeFromLiteral("\"1.7.2\"", token.STRING, 0)),

		// type definitions
		"Lute":        reflect.ValueOf((*lute.Lute)(nil)),
		"ParseOption": reflect.ValueOf((*lute.ParseOption)(nil)),
	}
}
