// Code generated by 'yaegi extract github.com/456vv/vmap/v2'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"github.com/456vv/vmap/v2"
	"reflect"
)

func init() {
	Symbols["github.com/456vv/vmap/v2/vmap"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewMap": reflect.ValueOf(vmap.NewMap),

		// type definitions
		"Map": reflect.ValueOf((*vmap.Map)(nil)),
	}
}
