// Code generated by 'yaegi extract github.com/88250/lute'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"github.com/88250/lute"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/88250/lute/lute"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"FormatNodeSync":          reflect.ValueOf(lute.FormatNodeSync),
		"New":                     reflect.ValueOf(lute.New),
		"ProtyleExportMdNodeSync": reflect.ValueOf(lute.ProtyleExportMdNodeSync),
		"RenderNodeBlockDOM":      reflect.ValueOf(lute.RenderNodeBlockDOM),
		"Version":                 reflect.ValueOf(constant.MakeFromLiteral("\"1.7.5\"", token.STRING, 0)),

		// type definitions
		"Lute":        reflect.ValueOf((*lute.Lute)(nil)),
		"ParseOption": reflect.ValueOf((*lute.ParseOption)(nil)),
	}
}
