// Code generated by 'yaegi extract github.com/456vv/vweb/v2/server'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"github.com/456vv/vweb/v2/server"
	"reflect"
)

func init() {
	Symbols["github.com/456vv/vweb/v2/server/server"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewGroup":         reflect.ValueOf(server.NewGroup),
		"ServerContextKey": reflect.ValueOf(&server.ServerContextKey).Elem(),
		"Version":          reflect.ValueOf(&server.Version).Elem(),

		// type definitions
		"Group":  reflect.ValueOf((*server.Group)(nil)),
		"Server": reflect.ValueOf((*server.Server)(nil)),
	}
}
