// Code generated by 'yaegi extract github.com/456vv/vconnpool/v3'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"context"
	"github.com/456vv/vconnpool/v3"
	"net"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/456vv/vconnpool/v3/vconnpool"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrConnAlreadyExists": reflect.ValueOf(&vconnpool.ErrConnAlreadyExists).Elem(),
		"ErrConnClose":         reflect.ValueOf(&vconnpool.ErrConnClose).Elem(),
		"ErrConnIdleMax":       reflect.ValueOf(&vconnpool.ErrConnIdleMax).Elem(),
		"ErrConnNotAvailable":  reflect.ValueOf(&vconnpool.ErrConnNotAvailable).Elem(),
		"ErrConnPoolClosed":    reflect.ValueOf(&vconnpool.ErrConnPoolClosed).Elem(),
		"ErrConnPoolMax":       reflect.ValueOf(&vconnpool.ErrConnPoolMax).Elem(),
		"ErrConnRAWRead":       reflect.ValueOf(&vconnpool.ErrConnRAWRead).Elem(),
		"PriorityContextKey":   reflect.ValueOf(&vconnpool.PriorityContextKey).Elem(),
		"ResolveAddr":          reflect.ValueOf(vconnpool.ResolveAddr),

		// type definitions
		"Addr":   reflect.ValueOf((*vconnpool.Addr)(nil)),
		"Conn":   reflect.ValueOf((*vconnpool.Conn)(nil)),
		"Dialer": reflect.ValueOf((*vconnpool.Dialer)(nil)),
		"Pool":   reflect.ValueOf((*vconnpool.Pool)(nil)),

		// interface wrapper definitions
		"_Conn":   reflect.ValueOf((*_github_com_456vv_vconnpool_v3_Conn)(nil)),
		"_Dialer": reflect.ValueOf((*_github_com_456vv_vconnpool_v3_Dialer)(nil)),
	}
}

// _github_com_456vv_vconnpool_v3_Conn is an interface wrapper for Conn type
type _github_com_456vv_vconnpool_v3_Conn struct {
	IValue            interface{}
	WClose            func() error
	WDiscard          func()
	WIsReuseConn      func() bool
	WLocalAddr        func() net.Addr
	WRawConn          func() net.Conn
	WRead             func(b []byte) (n int, err error)
	WRemoteAddr       func() net.Addr
	WSetDeadline      func(t time.Time) error
	WSetReadDeadline  func(t time.Time) error
	WSetWriteDeadline func(t time.Time) error
	WWrite            func(b []byte) (n int, err error)
}

func (W _github_com_456vv_vconnpool_v3_Conn) Close() error {
	return W.WClose()
}
func (W _github_com_456vv_vconnpool_v3_Conn) Discard() {
	W.WDiscard()
}
func (W _github_com_456vv_vconnpool_v3_Conn) IsReuseConn() bool {
	return W.WIsReuseConn()
}
func (W _github_com_456vv_vconnpool_v3_Conn) LocalAddr() net.Addr {
	return W.WLocalAddr()
}
func (W _github_com_456vv_vconnpool_v3_Conn) RawConn() net.Conn {
	return W.WRawConn()
}
func (W _github_com_456vv_vconnpool_v3_Conn) Read(b []byte) (n int, err error) {
	return W.WRead(b)
}
func (W _github_com_456vv_vconnpool_v3_Conn) RemoteAddr() net.Addr {
	return W.WRemoteAddr()
}
func (W _github_com_456vv_vconnpool_v3_Conn) SetDeadline(t time.Time) error {
	return W.WSetDeadline(t)
}
func (W _github_com_456vv_vconnpool_v3_Conn) SetReadDeadline(t time.Time) error {
	return W.WSetReadDeadline(t)
}
func (W _github_com_456vv_vconnpool_v3_Conn) SetWriteDeadline(t time.Time) error {
	return W.WSetWriteDeadline(t)
}
func (W _github_com_456vv_vconnpool_v3_Conn) Write(b []byte) (n int, err error) {
	return W.WWrite(b)
}

// _github_com_456vv_vconnpool_v3_Dialer is an interface wrapper for Dialer type
type _github_com_456vv_vconnpool_v3_Dialer struct {
	IValue       interface{}
	WDial        func(network string, address string) (net.Conn, error)
	WDialContext func(ctx context.Context, network string, address string) (net.Conn, error)
}

func (W _github_com_456vv_vconnpool_v3_Dialer) Dial(network string, address string) (net.Conn, error) {
	return W.WDial(network, address)
}
func (W _github_com_456vv_vconnpool_v3_Dialer) DialContext(ctx context.Context, network string, address string) (net.Conn, error) {
	return W.WDialContext(ctx, network, address)
}
