// Code generated by 'yaegi extract github.com/456vv/vforward/v2'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"github.com/456vv/vforward/v2"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/456vv/vforward/v2/vforward"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultReadBufSize": reflect.ValueOf(constant.MakeFromLiteral("65536", token.INT, 0)),

		// type definitions
		"D2D":     reflect.ValueOf((*vforward.D2D)(nil)),
		"D2DSwap": reflect.ValueOf((*vforward.D2DSwap)(nil)),
		"L2D":     reflect.ValueOf((*vforward.L2D)(nil)),
		"L2DSwap": reflect.ValueOf((*vforward.L2DSwap)(nil)),
		"L2L":     reflect.ValueOf((*vforward.L2L)(nil)),
		"L2LSwap": reflect.ValueOf((*vforward.L2LSwap)(nil)),
		"Option":  reflect.ValueOf((*vforward.Option)(nil)),
	}
}
