// Code generated by 'yaegi extract github.com/456vv/vweb/v3'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"bufio"
	"context"
	"github.com/456vv/vmap/v2"
	"github.com/456vv/vweb/v3"
	"io"
	"net"
	"net/http"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/456vv/vweb/v3/vweb"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddSalt":              reflect.ValueOf(vweb.AddSalt),
		"AutoCert":             reflect.ValueOf(vweb.AutoCert),
		"ConnContextKey":       reflect.ValueOf(&vweb.ConnContextKey).Elem(),
		"ExecFunc":             reflect.ValueOf(vweb.ExecFunc),
		"ForMethod":            reflect.ValueOf(vweb.ForMethod),
		"ForType":              reflect.ValueOf(vweb.ForType),
		"GenerateRandom":       reflect.ValueOf(vweb.GenerateRandom),
		"GenerateRandomID":     reflect.ValueOf(vweb.GenerateRandomID),
		"GenerateRandomString": reflect.ValueOf(vweb.GenerateRandomString),
		"ListenerContextKey":   reflect.ValueOf(&vweb.ListenerContextKey).Elem(),
		"NewSitePool":          reflect.ValueOf(vweb.NewSitePool),
		"PagePath":             reflect.ValueOf(vweb.PagePath),
		"PluginContextKey":     reflect.ValueOf(&vweb.PluginContextKey).Elem(),
		"PluginTypeHTTP":       reflect.ValueOf(vweb.PluginTypeHTTP),
		"PluginTypeRPC":        reflect.ValueOf(vweb.PluginTypeRPC),
		"RouterContextKey":     reflect.ValueOf(&vweb.RouterContextKey).Elem(),
		"SiteContextKey":       reflect.ValueOf(&vweb.SiteContextKey).Elem(),

		// type definitions
		"Cookie":               reflect.ValueOf((*vweb.Cookie)(nil)),
		"Cookier":              reflect.ValueOf((*vweb.Cookier)(nil)),
		"Dot":                  reflect.ValueOf((*vweb.Dot)(nil)),
		"DotContexter":         reflect.ValueOf((*vweb.DotContexter)(nil)),
		"Doter":                reflect.ValueOf((*vweb.Doter)(nil)),
		"DynamicTemplateFunc":  reflect.ValueOf((*vweb.DynamicTemplateFunc)(nil)),
		"DynamicTemplater":     reflect.ValueOf((*vweb.DynamicTemplater)(nil)),
		"ExecCall":             reflect.ValueOf((*vweb.ExecCall)(nil)),
		"ExitCall":             reflect.ValueOf((*vweb.ExitCall)(nil)),
		"Forward":              reflect.ValueOf((*vweb.Forward)(nil)),
		"ForwardRewriter":      reflect.ValueOf((*vweb.ForwardRewriter)(nil)),
		"Globaler":             reflect.ValueOf((*vweb.Globaler)(nil)),
		"HandleFunc":           reflect.ValueOf((*vweb.HandleFunc)(nil)),
		"PluginHTTP":           reflect.ValueOf((*vweb.PluginHTTP)(nil)),
		"PluginHTTPClient":     reflect.ValueOf((*vweb.PluginHTTPClient)(nil)),
		"PluginRPC":            reflect.ValueOf((*vweb.PluginRPC)(nil)),
		"PluginRPCClient":      reflect.ValueOf((*vweb.PluginRPCClient)(nil)),
		"PluginType":           reflect.ValueOf((*vweb.PluginType)(nil)),
		"Pluginer":             reflect.ValueOf((*vweb.Pluginer)(nil)),
		"Responser":            reflect.ValueOf((*vweb.Responser)(nil)),
		"Route":                reflect.ValueOf((*vweb.Route)(nil)),
		"Router":               reflect.ValueOf((*vweb.Router)(nil)),
		"ServerHandlerDynamic": reflect.ValueOf((*vweb.ServerHandlerDynamic)(nil)),
		"ServerHandlerStatic":  reflect.ValueOf((*vweb.ServerHandlerStatic)(nil)),
		"Session":              reflect.ValueOf((*vweb.Session)(nil)),
		"Sessioner":            reflect.ValueOf((*vweb.Sessioner)(nil)),
		"Sessions":             reflect.ValueOf((*vweb.Sessions)(nil)),
		"Site":                 reflect.ValueOf((*vweb.Site)(nil)),
		"SiteMan":              reflect.ValueOf((*vweb.SiteMan)(nil)),
		"SitePool":             reflect.ValueOf((*vweb.SitePool)(nil)),

		// interface wrapper definitions
		"_Cookier":          reflect.ValueOf((*_github_com_456vv_vweb_v3_Cookier)(nil)),
		"_DotContexter":     reflect.ValueOf((*_github_com_456vv_vweb_v3_DotContexter)(nil)),
		"_Doter":            reflect.ValueOf((*_github_com_456vv_vweb_v3_Doter)(nil)),
		"_DynamicTemplater": reflect.ValueOf((*_github_com_456vv_vweb_v3_DynamicTemplater)(nil)),
		"_Globaler":         reflect.ValueOf((*_github_com_456vv_vweb_v3_Globaler)(nil)),
		"_PluginHTTP":       reflect.ValueOf((*_github_com_456vv_vweb_v3_PluginHTTP)(nil)),
		"_PluginRPC":        reflect.ValueOf((*_github_com_456vv_vweb_v3_PluginRPC)(nil)),
		"_Pluginer":         reflect.ValueOf((*_github_com_456vv_vweb_v3_Pluginer)(nil)),
		"_Responser":        reflect.ValueOf((*_github_com_456vv_vweb_v3_Responser)(nil)),
		"_Router":           reflect.ValueOf((*_github_com_456vv_vweb_v3_Router)(nil)),
		"_Sessioner":        reflect.ValueOf((*_github_com_456vv_vweb_v3_Sessioner)(nil)),
	}
}

// _github_com_456vv_vweb_v3_Cookier is an interface wrapper for Cookier type
type _github_com_456vv_vweb_v3_Cookier struct {
	IValue     interface{}
	WAdd       func(name string, value string, path string, domain string, maxAge int, secure bool, only bool, sameSite http.SameSite)
	WDel       func(name string)
	WGet       func(name string) string
	WReadAll   func() map[string]string
	WRemoveAll func()
}

func (W _github_com_456vv_vweb_v3_Cookier) Add(name string, value string, path string, domain string, maxAge int, secure bool, only bool, sameSite http.SameSite) {
	W.WAdd(name, value, path, domain, maxAge, secure, only, sameSite)
}
func (W _github_com_456vv_vweb_v3_Cookier) Del(name string) {
	W.WDel(name)
}
func (W _github_com_456vv_vweb_v3_Cookier) Get(name string) string {
	return W.WGet(name)
}
func (W _github_com_456vv_vweb_v3_Cookier) ReadAll() map[string]string {
	return W.WReadAll()
}
func (W _github_com_456vv_vweb_v3_Cookier) RemoveAll() {
	W.WRemoveAll()
}

// _github_com_456vv_vweb_v3_DotContexter is an interface wrapper for DotContexter type
type _github_com_456vv_vweb_v3_DotContexter struct {
	IValue       interface{}
	WContext     func() context.Context
	WWithContext func(ctx context.Context)
}

func (W _github_com_456vv_vweb_v3_DotContexter) Context() context.Context {
	return W.WContext()
}
func (W _github_com_456vv_vweb_v3_DotContexter) WithContext(ctx context.Context) {
	W.WWithContext(ctx)
}

// _github_com_456vv_vweb_v3_Doter is an interface wrapper for Doter type
type _github_com_456vv_vweb_v3_Doter struct {
	IValue            interface{}
	WContext          func() context.Context
	WCookie           func() vweb.Cookier
	WDefer            func(call any, args ...any) error
	WGlobal           func() vweb.Globaler
	WHeader           func() http.Header
	WRequest          func() *http.Request
	WRequestLimitSize func(l int64) *http.Request
	WResponse         func() vweb.Responser
	WRootDir          func(path string) string
	WSaveStatic       func(path string) (wr io.WriteCloser, err error)
	WSession          func() vweb.Sessioner
	WSwap             func() *vmap.Map
	WWithContext      func(ctx context.Context)
}

func (W _github_com_456vv_vweb_v3_Doter) Context() context.Context {
	return W.WContext()
}
func (W _github_com_456vv_vweb_v3_Doter) Cookie() vweb.Cookier {
	return W.WCookie()
}
func (W _github_com_456vv_vweb_v3_Doter) Defer(call any, args ...any) error {
	return W.WDefer(call, args...)
}
func (W _github_com_456vv_vweb_v3_Doter) Global() vweb.Globaler {
	return W.WGlobal()
}
func (W _github_com_456vv_vweb_v3_Doter) Header() http.Header {
	return W.WHeader()
}
func (W _github_com_456vv_vweb_v3_Doter) Request() *http.Request {
	return W.WRequest()
}
func (W _github_com_456vv_vweb_v3_Doter) RequestLimitSize(l int64) *http.Request {
	return W.WRequestLimitSize(l)
}
func (W _github_com_456vv_vweb_v3_Doter) Response() vweb.Responser {
	return W.WResponse()
}
func (W _github_com_456vv_vweb_v3_Doter) RootDir(path string) string {
	return W.WRootDir(path)
}
func (W _github_com_456vv_vweb_v3_Doter) SaveStatic(path string) (wr io.WriteCloser, err error) {
	return W.WSaveStatic(path)
}
func (W _github_com_456vv_vweb_v3_Doter) Session() vweb.Sessioner {
	return W.WSession()
}
func (W _github_com_456vv_vweb_v3_Doter) Swap() *vmap.Map {
	return W.WSwap()
}
func (W _github_com_456vv_vweb_v3_Doter) WithContext(ctx context.Context) {
	W.WWithContext(ctx)
}

// _github_com_456vv_vweb_v3_DynamicTemplater is an interface wrapper for DynamicTemplater type
type _github_com_456vv_vweb_v3_DynamicTemplater struct {
	IValue   interface{}
	WExecute func(out io.Writer, dot any) error
	WParse   func(r io.Reader) (err error)
	WSetPath func(root string, page string)
}

func (W _github_com_456vv_vweb_v3_DynamicTemplater) Execute(out io.Writer, dot any) error {
	return W.WExecute(out, dot)
}
func (W _github_com_456vv_vweb_v3_DynamicTemplater) Parse(r io.Reader) (err error) {
	return W.WParse(r)
}
func (W _github_com_456vv_vweb_v3_DynamicTemplater) SetPath(root string, page string) {
	W.WSetPath(root, page)
}

// _github_com_456vv_vweb_v3_Globaler is an interface wrapper for Globaler type
type _github_com_456vv_vweb_v3_Globaler struct {
	IValue          interface{}
	WDel            func(key any)
	WGet            func(key any) any
	WHas            func(key any) bool
	WReset          func()
	WSet            func(key any, val any)
	WSetExpired     func(key any, d time.Duration)
	WSetExpiredCall func(key any, d time.Duration, f func(any))
}

func (W _github_com_456vv_vweb_v3_Globaler) Del(key any) {
	W.WDel(key)
}
func (W _github_com_456vv_vweb_v3_Globaler) Get(key any) any {
	return W.WGet(key)
}
func (W _github_com_456vv_vweb_v3_Globaler) Has(key any) bool {
	return W.WHas(key)
}
func (W _github_com_456vv_vweb_v3_Globaler) Reset() {
	W.WReset()
}
func (W _github_com_456vv_vweb_v3_Globaler) Set(key any, val any) {
	W.WSet(key, val)
}
func (W _github_com_456vv_vweb_v3_Globaler) SetExpired(key any, d time.Duration) {
	W.WSetExpired(key, d)
}
func (W _github_com_456vv_vweb_v3_Globaler) SetExpiredCall(key any, d time.Duration, f func(any)) {
	W.WSetExpiredCall(key, d, f)
}

// _github_com_456vv_vweb_v3_PluginHTTP is an interface wrapper for PluginHTTP type
type _github_com_456vv_vweb_v3_PluginHTTP struct {
	IValue                interface{}
	WCancelRequest        func(req *http.Request)
	WCloseIdleConnections func()
	WRegisterProtocol     func(scheme string, rt http.RoundTripper)
	WRoundTrip            func(r *http.Request) (resp *http.Response, err error)
	WServeHTTP            func(w http.ResponseWriter, r *http.Request)
	WType                 func() vweb.PluginType
}

func (W _github_com_456vv_vweb_v3_PluginHTTP) CancelRequest(req *http.Request) {
	W.WCancelRequest(req)
}
func (W _github_com_456vv_vweb_v3_PluginHTTP) CloseIdleConnections() {
	W.WCloseIdleConnections()
}
func (W _github_com_456vv_vweb_v3_PluginHTTP) RegisterProtocol(scheme string, rt http.RoundTripper) {
	W.WRegisterProtocol(scheme, rt)
}
func (W _github_com_456vv_vweb_v3_PluginHTTP) RoundTrip(r *http.Request) (resp *http.Response, err error) {
	return W.WRoundTrip(r)
}
func (W _github_com_456vv_vweb_v3_PluginHTTP) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	W.WServeHTTP(w, r)
}
func (W _github_com_456vv_vweb_v3_PluginHTTP) Type() vweb.PluginType {
	return W.WType()
}

// _github_com_456vv_vweb_v3_PluginRPC is an interface wrapper for PluginRPC type
type _github_com_456vv_vweb_v3_PluginRPC struct {
	IValue    interface{}
	WCall     func(name string, arg any) (any, error)
	WClose    func() error
	WDiscard  func() error
	WRegister func(value any)
	WType     func() vweb.PluginType
}

func (W _github_com_456vv_vweb_v3_PluginRPC) Call(name string, arg any) (any, error) {
	return W.WCall(name, arg)
}
func (W _github_com_456vv_vweb_v3_PluginRPC) Close() error {
	return W.WClose()
}
func (W _github_com_456vv_vweb_v3_PluginRPC) Discard() error {
	return W.WDiscard()
}
func (W _github_com_456vv_vweb_v3_PluginRPC) Register(value any) {
	W.WRegister(value)
}
func (W _github_com_456vv_vweb_v3_PluginRPC) Type() vweb.PluginType {
	return W.WType()
}

// _github_com_456vv_vweb_v3_Pluginer is an interface wrapper for Pluginer type
type _github_com_456vv_vweb_v3_Pluginer struct {
	IValue interface{}
	WHTTP  func(name string) (vweb.PluginHTTP, error)
	WRPC   func(name string) (vweb.PluginRPC, error)
}

func (W _github_com_456vv_vweb_v3_Pluginer) HTTP(name string) (vweb.PluginHTTP, error) {
	return W.WHTTP(name)
}
func (W _github_com_456vv_vweb_v3_Pluginer) RPC(name string) (vweb.PluginRPC, error) {
	return W.WRPC(name)
}

// _github_com_456vv_vweb_v3_Responser is an interface wrapper for Responser type
type _github_com_456vv_vweb_v3_Responser struct {
	IValue       interface{}
	WError       func(a0 string, a1 int)
	WFlush       func()
	WHeader      func() http.Header
	WHijack      func() (net.Conn, *bufio.ReadWriter, error)
	WPush        func(target string, opts *http.PushOptions) error
	WReadFrom    func(a0 io.Reader) (int64, error)
	WRedirect    func(a0 string, a1 int)
	WWrite       func(a0 []byte) (int, error)
	WWriteHeader func(a0 int)
	WWriteString func(a0 string) (int, error)
}

func (W _github_com_456vv_vweb_v3_Responser) Error(a0 string, a1 int) {
	W.WError(a0, a1)
}
func (W _github_com_456vv_vweb_v3_Responser) Flush() {
	W.WFlush()
}
func (W _github_com_456vv_vweb_v3_Responser) Header() http.Header {
	return W.WHeader()
}
func (W _github_com_456vv_vweb_v3_Responser) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	return W.WHijack()
}
func (W _github_com_456vv_vweb_v3_Responser) Push(target string, opts *http.PushOptions) error {
	return W.WPush(target, opts)
}
func (W _github_com_456vv_vweb_v3_Responser) ReadFrom(a0 io.Reader) (int64, error) {
	return W.WReadFrom(a0)
}
func (W _github_com_456vv_vweb_v3_Responser) Redirect(a0 string, a1 int) {
	W.WRedirect(a0, a1)
}
func (W _github_com_456vv_vweb_v3_Responser) Write(a0 []byte) (int, error) {
	return W.WWrite(a0)
}
func (W _github_com_456vv_vweb_v3_Responser) WriteHeader(a0 int) {
	W.WWriteHeader(a0)
}
func (W _github_com_456vv_vweb_v3_Responser) WriteString(a0 string) (int, error) {
	return W.WWriteString(a0)
}

// _github_com_456vv_vweb_v3_Router is an interface wrapper for Router type
type _github_com_456vv_vweb_v3_Router struct {
	IValue         interface{}
	WHandleFunc    func(url string, handler func(w http.ResponseWriter, r *http.Request))
	WHandleFuncDot func(url string, handler ...func(vweb.Doter))
	WServeHTTP     func(w http.ResponseWriter, r *http.Request)
}

func (W _github_com_456vv_vweb_v3_Router) HandleFunc(url string, handler func(w http.ResponseWriter, r *http.Request)) {
	W.WHandleFunc(url, handler)
}
func (W _github_com_456vv_vweb_v3_Router) HandleFuncDot(url string, handler ...func(vweb.Doter)) {
	W.WHandleFuncDot(url, handler...)
}
func (W _github_com_456vv_vweb_v3_Router) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	W.WServeHTTP(w, r)
}

// _github_com_456vv_vweb_v3_Sessioner is an interface wrapper for Sessioner type
type _github_com_456vv_vweb_v3_Sessioner struct {
	IValue          interface{}
	WDefer          func(call any, args ...any) error
	WDel            func(key any)
	WFree           func()
	WGet            func(key any) any
	WGetHas         func(key any) (val any, ok bool)
	WHas            func(key any) bool
	WReset          func()
	WSet            func(key any, val any)
	WSetExpired     func(key any, d time.Duration)
	WSetExpiredCall func(key any, d time.Duration, f func(any))
	WToken          func() string
}

func (W _github_com_456vv_vweb_v3_Sessioner) Defer(call any, args ...any) error {
	return W.WDefer(call, args...)
}
func (W _github_com_456vv_vweb_v3_Sessioner) Del(key any) {
	W.WDel(key)
}
func (W _github_com_456vv_vweb_v3_Sessioner) Free() {
	W.WFree()
}
func (W _github_com_456vv_vweb_v3_Sessioner) Get(key any) any {
	return W.WGet(key)
}
func (W _github_com_456vv_vweb_v3_Sessioner) GetHas(key any) (val any, ok bool) {
	return W.WGetHas(key)
}
func (W _github_com_456vv_vweb_v3_Sessioner) Has(key any) bool {
	return W.WHas(key)
}
func (W _github_com_456vv_vweb_v3_Sessioner) Reset() {
	W.WReset()
}
func (W _github_com_456vv_vweb_v3_Sessioner) Set(key any, val any) {
	W.WSet(key, val)
}
func (W _github_com_456vv_vweb_v3_Sessioner) SetExpired(key any, d time.Duration) {
	W.WSetExpired(key, d)
}
func (W _github_com_456vv_vweb_v3_Sessioner) SetExpiredCall(key any, d time.Duration, f func(any)) {
	W.WSetExpiredCall(key, d, f)
}
func (W _github_com_456vv_vweb_v3_Sessioner) Token() string {
	return W.WToken()
}
