// Code generated by 'yaegi extract github.com/456vv/x/sqltable'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"github.com/456vv/x/sqltable"
	"reflect"
)

func init() {
	Symbols["github.com/456vv/x/sqltable/sqltable"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewSQLTable": reflect.ValueOf(sqltable.NewSQLTable),
		"Prepare":     reflect.ValueOf(sqltable.Prepare),

		// type definitions
		"SQLTable": reflect.ValueOf((*sqltable.SQLTable)(nil)),
	}
}
