// Code generated by 'yaegi extract github.com/456vv/vbody'. DO NOT EDIT.

package yaegi_lib

import (
	"github.com/456vv/vbody"
	"reflect"
)

func init() {
	Symbols["github.com/456vv/vbody/vbody"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewReader": reflect.ValueOf(vbody.NewReader),
		"NewWriter": reflect.ValueOf(vbody.NewWriter),

		// type definitions
		"Change": reflect.ValueOf((*vbody.Change)(nil)),
		"Reader": reflect.ValueOf((*vbody.Reader)(nil)),
		"Writer": reflect.ValueOf((*vbody.Writer)(nil)),
	}
}
