// Code generated by 'yaegi extract github.com/456vv/vcipher'. DO NOT EDIT.

//go:build yaegi_lib
// +build yaegi_lib

package yaegi_lib

import (
	"github.com/456vv/vcipher"
	"reflect"
)

func init() {
	Symbols["github.com/456vv/vcipher/vcipher"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AES":       reflect.ValueOf(vcipher.AES),
		"NewCipher": reflect.ValueOf(vcipher.NewCipher),

		// type definitions
		"Cipher": reflect.ValueOf((*vcipher.Cipher)(nil)),
	}
}
